name: Deploy Vite React App to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_CONTACT_NAME: ${{ secrets.VITE_CONTACT_NAME }}
          VITE_CONTACT_EMAIL: ${{ secrets.VITE_CONTACT_EMAIL }}
          VITE_CONTACT_PHONE: ${{ secrets.VITE_CONTACT_PHONE }}
          VITE_CONTACT_STREET: ${{ secrets.VITE_CONTACT_STREET }}
          VITE_CONTACT_CITY_LINE: ${{ secrets.VITE_CONTACT_CITY_LINE }}
          VITE_CONTACT_CITY: ${{ secrets.VITE_CONTACT_CITY }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # WICHTIG: Wir laden nur den 'dist' Ordner hoch, den Vite erstellt hat!
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
